CREATE DATABASE IF NOT EXISTS users_db CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS orders_db CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON users_db.* TO 'gh_user'@'%';
GRANT ALL PRIVILEGES ON orders_db.* TO 'gh_user'@'%';
FLUSH PRIVILEGES;